### ISSUE TITLE
Compatibilidad con PHP7

### ISSUE THREAD

**Issue by luiscosio** [compropago/plugin-magento#20]
Al querer instalar el plugin, no me permite instalarlo por la versión de PHP:

CONNECT ERROR: Package community/Compropago_Payment_Extension 2.1.0: requires PHP version >= 5.5.0 and <= 6.0.0 current is: 7.0.13-0ubuntu0.16.04.1

¿Hay alguna manera de hacerlo funcionar en esta version de PHP?

La versión de Magento es la 1.9.3.1

**Comment by danteay** [comment]
Que tal @luiscosio 

Como tal no es complicado la única cuestión es que al momento de generar la extensión pedía un rango de versiones a soportar de PHP, y en su momento la configuración se genero cuando no era estable PHP 7, si me permites el día de hoy, voy a liberar unas nuevas características del plugin y en este caso actualizare la versión soportada para que puedas instalarlo correctamente.

Saludos.

**Comment by danteay** [comment]
@luiscosio Te informo que ya esta disponible la nueva versión 2.1.1 dentro de Magento Connect para que puedas descargarla y probarla.
