### ISSUE TITLE
no se crea la carpeta lib/ComproPago/

### ISSUE THREAD

**Issue by chukione** [compropago/plugin-magento#45]
la carpeta lib/ComproPago/ no se crea y el servidor web regresa un 500 porque no encuentra el archivo lib/ComproPago/vendor/autoload.php al ingresar a la sección metodos de pago de magento 1.x.

**Comment by javiertelioz** [comment]
Hola @chukione  el fix para esto es generar un **composer.json** en la carpeta **ComproPago** con este contenido:

`{
    "require": {
        "compropago/php-sdk": "^4.0"
    }
}
`
una vez generado, navega a donde esta la librería e ejecuta **composer install** esto corregira el error.


Saludos Javier.

**Comment by JoseBSX** [comment]
Hola; colocaremos la solución en en archivo README para la solución de este problema.

Saludos.
